/**
 * Rutas frontend: [modulo]/[seccion] en español (React Router).
 * Las APIs del backend siguen en /inventory/*, /finance/*, etc.
 */

export const APP_ROUTES = {
  dashboard: "/",
  operation: {
    cash: "/operacion/caja",
    shifts: "/operacion/turno",
    tasks: "/operacion/tareas",
    posReceipts: "/operacion/comprobantes-pos",
    shiftSupervision: "/operacion/supervision-caja",
    multiCash: "/operacion/turno/multi-caja",
  },
  electronicDocs: {
    hub: "/comprobantes-electronicos",
    invoices: "/comprobantes-electronicos/facturas",
    salesNotes: "/comprobantes-electronicos/notas-venta",
    creditNotes: "/comprobantes-electronicos/notas-credito",
    debitNotes: "/comprobantes-electronicos/notas-debito",
    withholdings: "/comprobantes-electronicos/retenciones",
    deliveryGuides: "/comprobantes-electronicos/guias-remision",
    purchaseSettlement: "/comprobantes-electronicos/liquidacion-compras",
    issued: "/comprobantes-electronicos/emitidos",
    sriSettings: "/sistema/configuracion?tab=sri",
  },
  sales: {
    orders: "/ventas/pedidos",
    customers: "/ventas/clientes",
    customerAccounts: "/ventas/clientes/cuentas",
  },
  finance: {
    transactions: "/finanzas/movimientos",
    collections: "/finanzas/cobranzas",
    loansDebts: "/finanzas/prestamos-deudas",
    recurringExpenses: "/finanzas/gastos-recurrentes",
  },
  inventory: {
    products: "/inventario/productos",
    movement: "/inventario/movimientos",
    categories: "/inventario/categorias",
    tierGroups: "/inventario/tramos",
    units: "/inventario/unidades",
    warehouses: "/inventario/bodegas",
    batches: "/inventario/lotes",
  },
  production: {
    ingredients: "/produccion/insumos",
    recipes: "/produccion/recetas",
    manufacturing: "/produccion/fabricacion",
    suppliers: "/produccion/proveedores",
    supplierAccounts: "/produccion/proveedores/cuentas",
  },
  channel: {
    catalog: "/canal/catalogo",
    stores: "/canal/locales",
    featuredProducts: "/canal/productos-destacados",
    compareGroups: "/canal/grupos-comparativos",
  },
  advertising: {
    campaigns: "/publicidad",
    devices: "/publicidad/dispositivos",
    player: "/publicidad/reproductor",
    campaignNew: "/publicidad/campanas/nueva",
    campaignEdit: (id) => `/publicidad/campanas/${id}`,
  },
  promoDesign: {
    editor: "/diseno-promocional/editor",
    preview: "/diseno-promocional/vista",
    templates: "/diseno-promocional/plantillas",
  },
  admin: {
    users: "/administracion/usuarios",
    accounts: "/administracion/cuentas",
    roles: "/administracion/roles",
    controlPanel: "/administracion/panel-control",
    notificationPrograms: "/administracion/programas-notificacion",
  },
  system: {
    settings: "/sistema/configuracion",
    plans: "/sistema/planes",
    modules: "/sistema/modulos",
    profile: "/sistema/perfil",
    donations: "/sistema/donaciones",
    notifications: "/sistema/notificaciones",
  },
  developer: {
    images: "/desarrollador/imagenes",
    files: "/desarrollador/archivos",
    logs: "/desarrollador/logs",
    backups: "/desarrollador/backups",
    commands: "/desarrollador/comandos",
  },
  public: {
    catalog: "/publico/catalogo",
    stores: "/publico/locales",
  },
  info: "/info",
};

/** Redirecciones legacy → rutas canónicas en español. */
export const LEGACY_ROUTE_REDIRECTS = [
  // Operación (flat)
  ["/caja", APP_ROUTES.operation.cash],
  ["/turno", APP_ROUTES.operation.shifts],
  ["/tareas", APP_ROUTES.operation.tasks],
  ["/facturacion", APP_ROUTES.operation.posReceipts],
  ["/turno/supervision", APP_ROUTES.operation.shiftSupervision],
  ["/turno/multi-caja", APP_ROUTES.operation.multiCash],
  ["/comprobantes", APP_ROUTES.operation.posReceipts],
  // Operación (inglés intermedio)
  ["/operation/cash", APP_ROUTES.operation.cash],
  ["/operation/shifts", APP_ROUTES.operation.shifts],
  ["/operation/tasks", APP_ROUTES.operation.tasks],
  ["/operation/pos-receipts", APP_ROUTES.operation.posReceipts],
  ["/operation/shift-supervision", APP_ROUTES.operation.shiftSupervision],
  ["/operation/shifts/multi-cash", APP_ROUTES.operation.multiCash],
  // Ventas
  ["/sales/orders", APP_ROUTES.sales.orders],
  ["/sales/customers", APP_ROUTES.sales.customers],
  ["/sales/customers/accounts", APP_ROUTES.sales.customerAccounts],
  ["/inventory/orders", APP_ROUTES.sales.orders],
  ["/inventory/customers", APP_ROUTES.sales.customers],
  ["/inventory/customers/cuentas", APP_ROUTES.sales.customerAccounts],
  // Finanzas
  ["/finance/transactions", APP_ROUTES.finance.transactions],
  ["/finance/collections", APP_ROUTES.finance.collections],
  ["/finance/loans-debts", APP_ROUTES.finance.loansDebts],
  ["/finance/recurring-expenses", APP_ROUTES.finance.recurringExpenses],
  ["/inventory/finance", APP_ROUTES.finance.transactions],
  ["/inventory/collections", APP_ROUTES.finance.collections],
  ["/inventory/prestamos-deudas", APP_ROUTES.finance.loansDebts],
  ["/inventory/gastos-recurrentes", APP_ROUTES.finance.recurringExpenses],
  // Inventario
  ["/inventory/products", APP_ROUTES.inventory.products],
  ["/inventory/movement", APP_ROUTES.inventory.movement],
  ["/inventory/categories", APP_ROUTES.inventory.categories],
  ["/inventory/tramos", APP_ROUTES.inventory.tierGroups],
  ["/inventory/tier-groups", APP_ROUTES.inventory.tierGroups],
  ["/inventory/units", APP_ROUTES.inventory.units],
  ["/inventory/bodegas", APP_ROUTES.inventory.warehouses],
  ["/inventory/warehouses", APP_ROUTES.inventory.warehouses],
  ["/inventory/lotes", APP_ROUTES.inventory.batches],
  ["/inventory/batches", APP_ROUTES.inventory.batches],
  // Producción
  ["/production/ingredients", APP_ROUTES.production.ingredients],
  ["/production/recipes", APP_ROUTES.production.recipes],
  ["/production/manufacturing", APP_ROUTES.production.manufacturing],
  ["/production/suppliers", APP_ROUTES.production.suppliers],
  ["/production/suppliers/accounts", APP_ROUTES.production.supplierAccounts],
  ["/inventory/insumos", APP_ROUTES.production.ingredients],
  ["/inventory/recipes", APP_ROUTES.production.recipes],
  ["/inventory/production", APP_ROUTES.production.manufacturing],
  ["/inventory/suppliers", APP_ROUTES.production.suppliers],
  ["/inventory/suppliers/cuentas", APP_ROUTES.production.supplierAccounts],
  // Canal
  ["/channel/catalog", APP_ROUTES.channel.catalog],
  ["/channel/stores", APP_ROUTES.channel.stores],
  ["/channel/featured-products", APP_ROUTES.channel.featuredProducts],
  ["/channel/compare-groups", APP_ROUTES.channel.compareGroups],
  ["/catalog_manager", APP_ROUTES.channel.catalog],
  ["/inventory/puntos-venta", APP_ROUTES.channel.stores],
  ["/inventory/productos-destacados", APP_ROUTES.channel.featuredProducts],
  ["/compare_groups", APP_ROUTES.channel.compareGroups],
  // Administración
  ["/admin/users", APP_ROUTES.admin.users],
  ["/admin/accounts", APP_ROUTES.admin.accounts],
  ["/admin/roles", APP_ROUTES.admin.roles],
  ["/admin/control-panel", APP_ROUTES.admin.controlPanel],
  ["/admin/notification-programs", APP_ROUTES.admin.notificationPrograms],
  ["/users", APP_ROUTES.admin.users],
  ["/cuentas", APP_ROUTES.admin.accounts],
  ["/roles", APP_ROUTES.admin.roles],
  ["/panel_control", APP_ROUTES.admin.controlPanel],
  ["/notification-programs", APP_ROUTES.admin.notificationPrograms],
  // Sistema
  ["/notifications", APP_ROUTES.system.notifications],
  ["/perfil", APP_ROUTES.system.profile],
  ["/donaciones", APP_ROUTES.system.donations],
  ["/app-settings", APP_ROUTES.system.settings],
  ["/sistema/facturacion-electronica", `${APP_ROUTES.system.settings}?tab=sri`],
  ["/facturacion/sri", `${APP_ROUTES.system.settings}?tab=sri`],
  // Desarrollador
  ["/img", APP_ROUTES.developer.images],
  ["/file", APP_ROUTES.developer.files],
  ["/logs", APP_ROUTES.developer.logs],
  ["/backups", APP_ROUTES.developer.backups],
  ["/comandos", APP_ROUTES.developer.commands],
  // Diseño promocional
  ["/editor", APP_ROUTES.promoDesign.editor],
  ["/editorDefault", APP_ROUTES.promoDesign.editor],
  ["/publicity_edit", APP_ROUTES.promoDesign.editor],
  ["/templates", APP_ROUTES.promoDesign.templates],
  // Público
  ["/public/catalog", APP_ROUTES.public.catalog],
  ["/public/stores", APP_ROUTES.public.stores],
  ["/catalogo", APP_ROUTES.public.catalog],
  ["/punto_venta", APP_ROUTES.public.stores],
  ["/backery", APP_ROUTES.public.catalog],
];
